Revert "[honeydew][wlan] Remove class `AccessPointState` 🎉"
This reverts commit c93309fd6ba092295844132366ac3fef20e0be47.

Reason for revert: "  File "/b/s/w/ir/prebuilt/third_party/python3/linux-x64/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AccessPointState is not JSON serializable"

Failure Link: b/543067591

Original change's description:
> [honeydew][wlan] Remove class `AccessPointState` 🎉
>
> Bug: 523267039
> Change-Id: I555c2b4205f3cbe6087e08c7831a33302686ba85
> Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1739812
> Reviewed-by: Marc Khouri <mnck@google.com>
> Fuchsia-Auto-Submit: Jerry Chou <jerrychou@google.com>
> Commit-Queue: Jerry Chou <jerrychou@google.com>

Bug: 523267039
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: If0d3dcc9c3e77749a6409cf57756be48add179c2
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1744031
Exempt: android-build-ayeaye@system.gserviceaccount.com <android-build-ayeaye@system.gserviceaccount.com>