[roll] Roll llvm-project/libc [libc][memory_utils] Rename shadowed load/store to avoid ADL ambiguity (#211714)
When compiling `inline_memmove` with MSVC for non-x86 architectures, `op_generic.h` picks
a non-builtin type for generic_v128 and friends:
https://github.com/llvm/llvm-project/blob/cad3c95a89c48d714a71f6e8b4af6f3e3ab100ea/libc/src/string/memory_utils/op_generic.h#L54-L57

This causes calls to `load` and `store` to trigger ADL, which is
ambiguous with `load` definition in `memory_utils/utils.h`.

```
C:\Users\jtstogel\Github\llvm-project\libc\src/string/memory_utils/op_generic.h(348): error C2668: '__llvm_libc_24_0_0_git::generic::store': ambiguous call to overloaded function
C:\Users\jtstogel\Github\llvm-project\libc\src/string/memory_utils/op_generic.h(138): note: could be 'void __llvm_libc_24_0_0_git::generic::store<T>(__llvm_libc_24_0_0_git::Ptr,T)'
        with
        [
            T=__llvm_libc_24_0_0_git::inline_memmove_aarch64::uint512_t
        ]
C:\Users\jtstogel\Github\llvm-project\libc\src/string/memory_utils/utils.h(221): note: or       'void __llvm_libc_24_0_0_git::store<T>(__llvm_libc_24_0_0_git::Ptr,T)' [found using argument-dependent lookup]
        with
        [
            T=__llvm_libc_24_0_0_git::inline_memmove_aarch64::uint512_t
        ]
C:\Users\jtstogel\Github\llvm-project\libc\src/string/memory_utils/op_generic.h(348): note: while trying to match the argument list '(__llvm_libc_24_0_0_git::Ptr, const T)'
        with
        [
            T=__llvm_libc_24_0_0_git::inline_memmove_aarch64::uint512_t
        ]
```
GitOrigin-RevId: 5337a2abb0b476d219cade1185b22890639ef9b8
Original-Revision: e0e4c1cea8829f33886e80b46bacbbdf2ee05906

Rolled-Repo: https://llvm.googlesource.com/llvm-project/libc
Rolled-Commits: 38ad267e45c65a..e0e4c1cea8829f
Roller-URL: https://cr-buildbucket.appspot.com/build/8675376641223185313
CQ-Do-Not-Cancel-Tryjobs: true
Cq-Include-Trybots: luci.turquoise.global.try:run-postsubmit-tryjobs
Change-Id: I4a584dca705f7733bdf852434ceef3784a1a7a1d
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1723730
Commit-Queue: global-integration-roller@fuchsia-infra.iam.gserviceaccount.com <global-integration-roller@fuchsia-infra.iam.gserviceaccount.com>